### ISSUE TITLE
streamline the snap installation logic with the official snap.v2 operator

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/charm-microcloud#3]
The charm currently installs its required dependencies using many subprocess calls like:
```python
subprocess.run(
       ["snap", "install", "lxd", f"--channel={lxd_channel}"] + cohort,
)
```

Instead, we want to manage the snaps using https://charmhub.io/operator-libs-linux/libraries/snap

**Comment by tomponline** [comment]
Lets do this one now as part of the initial PR https://github.com/canonical/charm-microcloud/pull/2

**Comment by gabrielmougard** [comment]
@tomponline I updated #2 to make use of the snap operator
